apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "postfix.fullname" . }}
  labels:
    app: {{ template "postfix.name" . }}
    chart: {{ template "postfix.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "postfix.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "postfix.name" . }}
        release: {{ .Release.Name }}
    spec:
{{- if eq (include "postfix.dkimActive" .) "true" }}
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - {{ default "localhost" .Values.postfixRelay.dkimMilterHost | quote }}
{{- end }}
      serviceAccountName: {{ template "postfix.serviceAccountName" . }}
{{- if or .Values.postfix.image.imagepullsecrets .Values.dkim.image.imagepullsecrets .Values.exporter.image.imagepullsecrets }}
      imagePullSecrets:
{{- toYaml ((concat .Values.postfix.image.imagepullsecrets .Values.dkim.image.imagepullsecrets .Values.exporter.image.imagepullsecrets) | uniq) | nindent 8 }}
{{- end }}
      containers:
      - name: {{ template "postfix.name" . }}
        image: '{{ .Values.postfix.image.repository }}:{{ default .Chart.AppVersion .Values.postfix.image.tag }}'
        imagePullPolicy: {{ .Values.postfix.image.pullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ template "postfix.fullname" . }}-postfix
          - secretRef:
              name: {{ template "postfix.fullname" . }}-postfix
        ports:
          - name: smtp
            containerPort: 25
        volumeMounts:
          - mountPath: /var/spool/postfix/
            name: metrics
          - mountPath: /data/log/
            name: logs
        resources:
{{ toYaml .Values.postfix.resources | indent 10 }}
{{- if .Values.exporter.enabled }}
      - name: {{ template "postfix.name" . }}-exporter
        image: '{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}'
        imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
        args:
          - --postfix.logfile_path=/data/log/maillog
          - --postfix.showq_path=/var/spool/postfix/public/showq
        ports:
          - name: exporter
            containerPort: {{ .Values.service.exporterPort }}
        volumeMounts:
          - mountPath: /var/spool/postfix/
            name: metrics
          - mountPath: /data/log/
            name: logs
        resources:
{{ toYaml .Values.exporter.resources | indent 10 }}
{{ end }}
{{- if eq (include "postfix.dkimActive" .) "true" }}
      - name: {{ template "postfix.name" . }}-dkimmilter
        image: '{{ .Values.dkim.image.repository }}:{{ .Values.dkim.image.tag }}'
        imagePullPolicy: {{ .Values.dkim.image.pullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ template "postfix.fullname" . }}-postfix
          - secretRef:
              name: {{ template "postfix.fullname" . }}-postfix
        resources:
{{ toYaml .Values.dkim.resources | indent 10 }}
{{ end }}
      volumes:
        - name: metrics
          emptyDir: {}
        - name: logs
          emptyDir: {}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
