{{- if .Values.postfixRelay.csi }}
  {{- if .Values.postfixRelay.csi.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "postfix.fullname" . }}-postfix
  labels:
    app: {{ template "postfix.name" . }}
    chart: {{ template "postfix.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  provider: {{ .Values.postfixRelay.csi.provider }}
  parameters:
    roleName: {{ template "postfix.fullname" . }}
    vaultAddress: {{ .Values.postfixRelay.csi.address }}
    objects: |
      - objectName: "POSTFIX_RELAY_DEFAULT_OUTBOUND_RELAY_PASSWORD"
        secretPath: "{{ .Release.Namespace | default "default" }}/data/postfixRelay"
        secretKey: "POSTFIX_RELAY_DEFAULT_OUTBOUND_RELAY_PASSWORD"
      {{- if eq (include "postfix.dkimActive" .) "true" }}
        {{- if and .Values.postfixRelay.defaultOutboundRelay.dkimDomain .Values.postfixRelay.defaultOutboundRelay.dkimSelector .Values.postfixRelay.defaultOutboundRelay.dkimFilter }}
      - objectName: "POSTFIX_RELAY_DEFAULT_OUTBOUND_RELAY_DKIM_KEY"
        secretPath: "{{ .Release.Namespace | default "default" }}/data/postfixRelay"
        secretKey: "POSTFIX_RELAY_DEFAULT_OUTBOUND_RELAY_DKIM_KEY"
        {{- end }}
      {{- end }}
      {{- if or (eq .Values.postfixRelay.inboundTls "may") (eq .Values.postfixRelay.inboundTls "encrypt") }}
      - objectName: "POSTFIX_RELAY_INBOUND_TLS_KEY"
        secretPath: "{{ .Release.Namespace | default "default" }}/data/postfixRelay"
        secretKey: "POSTFIX_RELAY_INBOUND_TLS_KEY"
      {{- end }}
      {{- if .Values.postfixRelay.additionalOutBoundRelay }}
        {{- range $i, $s := .Values.postfixRelay.additionalOutBoundRelay }}
      - objectName: "POSTFIX_RELAY_ADDITIONAL_OUTBOUND_RELAY_{{ $i }}_PASSWORD"
        secretPath: "{{ $.Release.Namespace | default "default" }}/data/postfixRelay"
        secretKey: "POSTFIX_RELAY_ADDITIONAL_OUTBOUND_RELAY_{{ $i }}_PASSWORD"
          {{- if eq (include "postfix.dkimActive" $) "true" }}
            {{- if and $s.dkimDomain $s.dkimSelector $s.dkimFilter }}
      - objectName: "POSTFIX_RELAY_ADDITIONAL_OUTBOUND_RELAY_{{ $i }}_DKIM_KEY"
        secretPath: "{{ $.Release.Namespace | default "default" }}/data/postfixRelay"
        secretKey: "POSTFIX_RELAY_ADDITIONAL_OUTBOUND_RELAY_{{ $i }}_DKIM_KEY"
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
  secretObjects:
    - secretName: {{ template "postfix.fullname" . }}-postfix
      type: Opaque
      data:
        - objectName: "POSTFIX_RELAY_DEFAULT_OUTBOUND_RELAY_PASSWORD"
          key: "POSTFIX_RELAY_DEFAULT_OUTBOUND_RELAY_PASSWORD"
    {{- if eq (include "postfix.dkimActive" .) "true" }}
      {{- if and .Values.postfixRelay.defaultOutboundRelay.dkimDomain .Values.postfixRelay.defaultOutboundRelay.dkimSelector .Values.postfixRelay.defaultOutboundRelay.dkimFilter }}
        - objectName: "POSTFIX_RELAY_DEFAULT_OUTBOUND_RELAY_DKIM_KEY"
          key: "POSTFIX_RELAY_DEFAULT_OUTBOUND_RELAY_DKIM_KEY"
      {{- end }}
    {{- end }}
    {{- if or (eq .Values.postfixRelay.inboundTls "may") (eq .Values.postfixRelay.inboundTls "encrypt") }}
        - objectName: "POSTFIX_RELAY_INBOUND_TLS_KEY"
          key: "POSTFIX_RELAY_INBOUND_TLS_KEY"
    {{- end }}
    {{- if .Values.postfixRelay.additionalOutBoundRelay }}
      {{- range $i, $s := .Values.postfixRelay.additionalOutBoundRelay }}
        - objectName: "POSTFIX_RELAY_ADDITIONAL_OUTBOUND_RELAY_{{ $i }}_PASSWORD"
          key: "POSTFIX_RELAY_ADDITIONAL_OUTBOUND_RELAY_{{ $i }}_PASSWORD"
        {{- if eq (include "postfix.dkimActive" $) "true" }}
          {{- if and $s.dkimDomain $s.dkimSelector $s.dkimFilter }}
        - objectName: "POSTFIX_RELAY_ADDITIONAL_OUTBOUND_RELAY_{{ $i }}_DKIM_KEY"
          key: "POSTFIX_RELAY_ADDITIONAL_OUTBOUND_RELAY_{{ $i }}_DKIM_KEY"
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}